dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
language: csharp
mono: none

install:
  - nvm install 10.16.3
  - nvm use 10.16.3
  - npm install
  - npm install nerdbank-gitversioning

script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - node getVersion.js
  - export SEMVER=$(node getVersion.js)
  - echo $SEMVER